### PR TITLE
Added template tag for rendering:

### PR DESCRIPTION
**Pull request by SalahAdDin**
It's very simple but it works:
```html
{% load i18n wagtailgeowidget_tags %}
<div>
    {% render_map self.map 'map' %}
    <p><strong>{% trans 'Address' %}:</strong> {{ self.address }}</p>
</div>
```

i have only a problem with it: it must have to have a class name, if you don't pass a class name as second value, it will give you a error.

Actually this class could be needed because styling is needed for the container, but, maybe this requierement could be not good.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
I was thinking: This approach only works with a one single map, but maybe someone wants to use it with more than one map. So, can you help me to improve it?

**Comment by marteinn** [comment]
Hi @SalahAdDin and thanks for the PR! I will look through this as soon as possible and provide feedback.

**Comment by SalahAdDin** [comment]
@marteinn What's about it?

**Comment by marteinn** [comment]
Hi @SalahAdDin!

Sorry for the long wait, I've been thinking long and hard about this PR and overall regarding including a client based map (as a complement to the internal admin map) and I'm honestly leaning towards a much simplier solution using static google maps (https://developers.google.com/maps/documentation/static-maps/), that wouldn't require any js or custom css. The reason is that I feel that maintaining a more rich map falls outside the scope of this library, that has the goal to provide a good editing experience for admin users.

When it comes to this PR, my motivation for not merging, in addition to my point below it is that I feel that exposing the map, that is now dedicated for the admin user (`initMap`) to the front user would make it harder for us to make changes in the interface in the future (since any exposed interface falls into the category of maintaining a stable api).

**Comment by SalahAdDin** [comment]
@marteinn The idea, for user's confort, is implements a tag for render maps.

But yes, we have other problems: if user wants put many maps, how can we handle it?

**Comment by SalahAdDin** [comment]
@marteinn I choosed split this tag in two tags, one loading the google api scripts, and other for render a single map. But i have a problem with this approaching, it breaks this `preview` section in `wagtail` admin. XD

**Comment by marteinn** [comment]
Hi @SalahAdDin! There seem to be some confusion regarding this PR (that I closed yesterday), so just to set the record straight:

- I wont accept a PR with a map based on the internal admin map, because exposing the map would require us to freeze the map api (besides this map was never ment to be served to front users).
- Our goal now is to integrate a simple templatetag based on the static image api (https://developers.google.com/maps/documentation/static-maps/), the reasons is that it has a small maintenance footprint.
- And finally to answer you question regarding embedding multiple maps, It is supported in the admin interface and we do it among other places on related models with maps embedded (check the example catalog in root).

I will use this issue for discussions regarding the templatetag: https://github.com/Frojd/wagtail-geo-widget/issues/7

**Pull request closed without merging**
