### PR TITLE
Wagtail 4.2 upgrade

### PR DESCRIPTION
**Pull request by katdom13**
Release notes: https://docs.wagtail.org/en/stable/releases/4.2.html

- Dropped support for Wagtail versions < 4.1
- Code cleanup

Tests are OK

```
Found 14 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..............
----------------------------------------------------------------------
Ran 14 tests in 0.130s

OK
```

### CODE REVIEW

**Comment by marteinn** [comment]
Hi @katdom13 and thanks for the PR! Sadly I cant accept this PR as it removes support for Wagtail 4.1, the thing is that Wagtail 2.15 is still supported until 2023-09-05 (https://endoflife.date/wagtail) and we want to keep supporting the maintained Wagtail versions. Another thing, please base your PR on the `develop` branch, we use git-flow on this project (sorry if that's unclear).

**Comment by katdom13** [comment]
> Hi @katdom13 and thanks for the PR! Sadly I cant accept this PR as it removes support for Wagtail 4.1, the thing is that Wagtail 2.15 is still supported until 2023-09-05 (https://endoflife.date/wagtail) and we want to keep supporting the maintained Wagtail versions. Another thing, please base your PR on the `develop` branch, we use git-flow on this project (sorry if that's unclear).

Hi @marteinn ,
I have rebased off of `develop` and I can see that you've already added a pre-release version of Wagtail 4.2 prior to this PR.

This PR aimed to drop support for Wagtail < 4.1, but if you still want 2.15 to be supported, I reverted those code cleanup changes, and nothing much is left.

With that, I just ran some linters and changed the Wagtail 4.2rc1 to 4.2.

Thank you!

**Comment by marteinn** [comment]
Hi @katdom13, I checked your latest changes and they seems to include my CI version bump and a code formatting in migrations (I recommend against linting/formatting as they are generated through Django, it's better to let Django own those) . Since this PR has changed a lot since the original I think we should do this, revert back to the old PR and lets resume this work once Wagtail 2.15 goes EOL. How does that sound?

**Comment by victoriachan** [comment]
Hi @marteinn, I'm wondering if this can go forward. According to the [link](https://endoflife.date/wagtail) you mentioned, both active and security support for Wagtail 2.15 ended on 01 Feb 2023. The only actively support versions (as of today) are 4.1 LTS and 4.2.

**Comment by marteinn** [comment]
Hi @victoriachan! I agree, it's time that we drop Wagtail < 4.1 support as those are EOL. Can you adjust your previous PR to include those changes? Thanks!

**Comment by marteinn** [comment]
Wagtail < 4.1 support has been dropped in https://github.com/Frojd/wagtail-geo-widget/releases/tag/v8.0.0, closing PR.

**Pull request closed without merging**
