### PR TITLE
:tada: implements places API

### PR DESCRIPTION
**Pull request by nickhudkins**
I had some users ask why the search box wasn't using Google Places search box, and I thought "That's a great question", so I made it so.

I also noticed that if this is in anything other than the first tab of the wagtail admin, the map does not initialize properly, so I added in a fix for that. If you'd like me to break that work out into a separate PR, let me know, I know some folks don't like mixed feature / bug fixes.

### CODE REVIEW

**Comment by marteinn** [comment]
Thanks for the PR @nickhudkins! I will review you changes and get back to you as soon as possible.

**Comment by marteinn** [comment]
Just tried out and it works great! I assume its the `checkVisibility()` method that fixes the tab bug? I will merge this and just do a little refactoring/style updates before pushing upstream.

Awesome work 👍

**Comment by nickhudkins** [comment]
Sounds good to me!

**Comment by marteinn** [comment]
I went through the code and realised that there were no handlers arranged for the autocomplete api (`place_changed`), so I went ahead and implemented it. The autocomplete vs geocode is a little bit weird, but seems to do the trick. Whats your opinion @nickhudkins?  https://github.com/Frojd/wagtail-geo-widget/commit/52028f2d723440d5178c4a64df5847a61ce0fc3a

**Comment by nickhudkins** [comment]
Ooo! I hadn't considered that, but I think that makes sense. It's a shame that the places don't always have geometry, but this seems to be a good solution. Thanks for cleaning this up too! checkVisibility is indeed what fixes the tab bug.

**Pull request merged**
